"""Tests for all sktime probabilistic forecasting metrics."""

import numpy as np
import pandas as pd
import pytest

from sktime.base._proba._normal import Normal
from sktime.split import temporal_train_test_split
from sktime.tests.test_all_estimators import BaseFixtureGenerator, QuickTester
from sktime.utils._testing.series import _make_series

# metrics known to fail on standard distribution input, tracked separately
# see issue for SquaredDistrLoss raising on evaluate with a single-variable Normal
_XFAIL_ON_DISTR = {"SquaredDistrLoss"}


def _make_quantile_pred(y_test, alphas=(0.05, 0.5, 0.95)):
    """Build a pred_quantiles DataFrame for a single-variable y_test."""
    cols = {}
    for alpha in alphas:
        cols[(0, alpha)] = (
            y_test.values * np.random.uniform(0.9, 1.1, len(y_test)) * (0.5 + alpha)
        )
    return pd.DataFrame(cols, index=y_test.index)


def _make_interval_pred(y_test, coverage=0.9):
    """Build a pred_interval DataFrame for a single-variable y_test."""
    cols = {
        (0, coverage, "lower"): y_test.values
        * np.random.uniform(0.9, 1.1, len(y_test))
        * (1 - coverage),
        (0, coverage, "upper"): y_test.values
        * np.random.uniform(0.9, 1.1, len(y_test))
        * (1 + coverage),
    }
    return pd.DataFrame(cols, index=y_test.index)


class ForecastingProbaMetricFixtureGenerator(BaseFixtureGenerator):
    """Fixture generator for probabilistic forecasting metric tests.

    Fixtures parameterized
    ----------------------
    object_class: estimator inheriting from BaseObject
        ranges over estimator classes not excluded by EXCLUDE_ESTIMATORS, EXCLUDED_TESTS
    object_instance: instance of estimator inheriting from BaseObject
        ranges over estimator classes not excluded by EXCLUDE_ESTIMATORS, EXCLUDED_TESTS
        instances are generated by create_test_instance class method
    scenario: instance of TestScenario
        ranges over all scenarios returned by retrieve_scenarios
    """

    # note: this should be separate from TestAllForecastingProbaMetrics
    #   additional fixtures, parameters, etc should be added here
    #   TestAllForecastingProbaMetrics should contain the tests only

    object_type_filter = "metric_forecasting_proba"

    fixture_sequence = [
        "object_class",
        "object_instance",
        "fitted_estimator",
        "scenario",
    ]


class TestAllForecastingProbaMetrics(
    ForecastingProbaMetricFixtureGenerator, QuickTester
):
    """Module level tests for all sktime probabilistic forecasting metrics."""

    def test_evaluate_output(self, object_instance):
        """Test that every proba metric evaluates on input of its declared scitype.

        The metric is fed the y_pred scitype it declares via ``scitype:y_pred``
        (pred_quantiles, pred_interval, or pred_proba), and the output type is
        checked against the documented contract for the default parameters.
        """
        metric = object_instance
        y_pred_scitype = metric.get_tag("scitype:y_pred")

        if y_pred_scitype in ("pred_quantiles", "pred_interval"):
            y = _make_series(n_timepoints=20, random_state=42)
            _, y_test = temporal_train_test_split(y)

            if y_pred_scitype == "pred_quantiles":
                # cover the metric's own requested quantiles, if any are set
                alphas = {0.05, 0.5, 0.95}
                requested = metric.get_params().get("alpha")
                if requested is not None:
                    alphas |= set(np.atleast_1d(requested).tolist())
                y_pred = _make_quantile_pred(y_test, sorted(alphas))
            else:
                y_pred = _make_interval_pred(y_test)

            # default multioutput + score_average average to a scalar loss
            loss = metric(y_true=y_test, y_pred=y_pred)
            assert isinstance(loss, float)

            by_index = metric.evaluate_by_index(y_true=y_test, y_pred=y_pred)
            assert isinstance(by_index, pd.Series)
            assert len(by_index) == len(y_test)

        elif y_pred_scitype == "pred_proba":
            if type(metric).__name__ in _XFAIL_ON_DISTR:
                pytest.xfail(
                    f"{type(metric).__name__} raises on evaluate with a "
                    "single-variable Normal; tracked separately"
                )

            y_pred = Normal.create_test_instance()
            y_true = y_pred.sample()

            loss = metric.evaluate(y_true, y_pred)
            assert isinstance(loss, pd.DataFrame)
            assert loss.shape[0] == 1

            by_index = metric.evaluate_by_index(y_true, y_pred)
            assert isinstance(by_index, pd.DataFrame)
            assert by_index.shape[0] == y_true.shape[0]

        else:
            raise AssertionError(
                f"unexpected scitype:y_pred tag {y_pred_scitype!r} on "
                f"{type(metric).__name__}"
            )
